# ── Groq Cache Fix ─────────────────────────────────────
try:
    from crewai.llms import cache as _cache
    _cache.mark_cache_breakpoint = lambda msg: msg
except ImportError:
    pass

import streamlit as st
import os
import io  # 🌟 NEW: Virtual Memory (RAM) ke liye
from docx import Document  # 🌟 NEW: Word Document Blueprint ke liye
from crewai import Agent, Task, Crew, LLM

st.set_page_config(page_title="Creator AI OS", layout="wide")

# ── API Keys ───────────────────────────────────────────
GEMINI_KEY = st.secrets.get("GEMINI_API_KEY", "")
GROQ_KEY   = st.secrets.get("GROQ_API_KEY", "")

if not GEMINI_KEY and not GROQ_KEY:
    st.sidebar.error("⚠️ Koi bhi API key set nahi hai!")

# ── LLM Objects — LiteLLM Provider Fixed ───────────────
def get_gemini_llm():
    return LLM(
        model="gemini/gemini-2.5-flash",
        api_key=GEMINI_KEY,
        timeout=60,
        max_retries=4
    )

def get_groq_llm():
    return LLM(
        model="groq/llama-3.3-70b-versatile",
        api_key=GROQ_KEY,
        temperature=0.7
    )

# 🌟 NEW HELPER FUNCTION: Script ko Word File (.docx) me badalna RAM ke andar
def create_word_doc(script_text, platform_name, topic_name):
    doc = Document()
    
    # Word file ke andar ka styling aur content structure
    doc.add_heading(f"🎬 Production Blueprint: {topic_name}", level=1)
    doc.add_paragraph(f"Target Platform: {platform_name}")
    doc.add_paragraph("Generated by: Creator AI OS (Multi-Agent System)")
    doc.add_paragraph("="*50)
    
    doc.add_heading("📝 Video Script Content", level=2)
    doc.add_paragraph(script_text)
    
    # File ko temporary RAM memory me save karna
    bio = io.BytesIO()
    doc.save(bio)
    bio.seek(0)  # Pointer ko shuruat me lana download ke liye
    return bio

# ── Session State ──────────────────────────────────────
if "niche_data"    not in st.session_state: st.session_state["niche_data"]    = ""
if "script_data"   not in st.session_state: st.session_state["script_data"]   = ""
if "active_model"  not in st.session_state: st.session_state["active_model"]  = ""
if "gemini_error"  not in st.session_state: st.session_state["gemini_error"]  = ""

# ── CrewAI Backend ─────────────────────────────────────
def run_crew(niche_topic, social_platform, output_language, llm, target_words, target_seconds):
    trend_researcher = Agent(
        role="Senior Content Trend Analyst",
        goal=f"Analyze what hooks people on '{niche_topic}' for {social_platform}.",
        backstory="Expert in viral retention algorithms. Knows what sub-topics trend right now.",
        llm=llm,
        max_iter=2,
        max_rpm=5,
        allow_delegation=False,
        verbose=True
    )

    script_writer = Agent(
        role="Expert Social Media Script Writer",
        goal=f"Create a viral script blueprint in {output_language} from the research.",
        backstory="Disciplined scriptwriter who turns raw research into high-retention video blueprints.",
        llm=llm,
        max_iter=2,
        max_rpm=5,
        allow_delegation=False,
        verbose=True
    )

    research_task = Task(
        description=f"Find 3 viral angles/hooks for: '{niche_topic}' on {social_platform}. Respond in {output_language}.",
        expected_output=f"Top 3 viral hooks in {output_language} language.",
        agent=trend_researcher
    )

    write_script_task = Task(
        description=f"""Using the 3 viral angles, create a complete 'Content Production Bundle' for {social_platform}.
        
        STRICT RULE 1: The ENTIRE bundle must be written in {output_language} language only.
        
        STRICT RULE 2 (EXACT DURATION CONTROL): The SECTION 1 (Script Blueprint) must be perfectly paced for a video of exactly {video_duration} MINUTES ({target_seconds} SECONDS). To achieve this, write exactly around {target_words} words for the script section. Do not shortcut this!
        
        You must format the output exactly into these 4 clear sections:
        
        ---
        SECTION 1: 🎬 VIDEO SCRIPT BLUEPRINT
        Write a complete high-retention script for {social_platform}. 
        Format like this: [00:00-00:05] Hook, Visual Description, Dialogues.
        
        ---
        SECTION 2: 🚀 VIRAL METADATA BUNDLE
        - 3 High-CTR Clickable Titles
        - SEO Description (2 lines)
        - 10 High-Volume Target Keywords
        
        ---
        SECTION 3: 📸 INSTAGRAM REELS / SHORTS EXTENSION
        - Short Viral Caption for social feed
        - 15 Trending & Niche Hashtags (#)
        
        ---
        SECTION 4: 🐦 X (TWITTER) / LINKEDIN TEXT THREAD
        - Convert the core summary of this script into a 3-part textual post/thread to post directly on X or LinkedIn.
        """,
        expected_output=f"A complete formatted production bundle including script, metadata, social captions, and text thread strictly in {output_language} language.",
        agent=script_writer
    )

    crew = Crew(
        agents=[trend_researcher, script_writer],
        tasks=[research_task, write_script_task],
        verbose=True
    )

    return str(crew.kickoff())

def run_my_crew_ai_agents(niche_topic, social_platform, output_language, video_duration):
    """Duration ko exact words aur seconds me convert karke Crew ko dena."""
    
    # 🌟 NEW ACCURATE MATH ENGINE
    target_seconds = int(video_duration * 60) # 0.5 min * 60 = 30 Seconds exact
    target_words = int(video_duration * 140)   # 0.5 min * 140 = 70 Words exact
    
    if GEMINI_KEY:
        try:
            st.session_state["gemini_error"] = ""
            gemini_llm = get_gemini_llm()
            # Yahan hum target_seconds aur target_words dono bhej rahe hain
            result = run_crew(niche_topic, social_platform, output_language, gemini_llm, target_words, target_seconds)
            st.session_state["active_model"] = "gemini"
            return result
        except Exception as e:
            st.session_state["gemini_error"] = str(e)

    if GROQ_KEY:
        st.session_state["active_model"] = "groq"
        groq_llm = get_groq_llm()
        return run_crew(niche_topic, social_platform, output_language, groq_llm, target_words, target_seconds)

    st.error("❌ Koi LLM available nahi!")
    st.stop()

# ── Sidebar ────────────────────────────────────────────
with st.sidebar:
    st.title("⚙️ Control Panel")
    platform = st.selectbox("Platform:", ["YouTube", "Instagram", "Facebook", "X (Twitter)"])
    language = st.selectbox("Language:", ["Hinglish", "Hindi", "English"])
    st.write("---")
    
    with st.expander("🔧 Debug Info", expanded=False):
        model = st.session_state.get("active_model", "N/A")
        display_engine = "Advanced Gemini Neural Core" if model == "gemini" else "Hyper-Speed Llama Engine" if model == "groq" else "N/A"
        st.write(f"Active Infrastructure: **{display_engine}**")
        err = st.session_state.get("gemini_error", "")
        if err:
            st.caption(f"Logs: {err[:150]}")
    st.write("---")
    st.caption("Powered by Gemini + Groq & CrewAI")

# ── Main UI ────────────────────────────────────────────
st.title("🚀 Creator AI Manager")
st.write(f"**{platform}** manager active | Language: **{language}**")
st.write("---")

tab1, tab2, tab3 = st.tabs(["🔥 Trend & Script", "📝 Generated Script", "📊 Analytics"])

with tab1:
    st.markdown("### 🔥 AI Content Strategy Hub")
    st.caption("Topic daliye — Researcher + Writer agents kaam karenge.")
    st.write("---")

    if st.session_state["gemini_error"]:
        st.info("ℹ️ **System Optimization:** Main Neural Grid busy hone ki wajah se app ne automatic secondary cloud processor ko route kar diya hai. Script uninterrupted taiyar ho chuki hai!")

    with st.form("trend_form"):
        user_niche = st.text_input(
            "🎯 Kis topic par video banani hai?",
            value=st.session_state["niche_data"],
            placeholder="E.g., What is AGI, Stoicism Guide, Python for Beginners..."
        )
        
        # 🌟 NEW: Duration Slider (30 Sec se lekar 20 Mins tak)
        # Value ko hum float (decimal) mein rakhenge taaki 0.5 ka matlab 30 seconds ho
        video_duration = st.slider(
            "⏱️ Video ki duration kitni honi chahiye? (In Minutes)",
            min_value=0.5,    # 0.5 mins = 30 Seconds
            max_value=20.0,   # 20 Minutes
            value=2.0,        # Default 2 minutes
            step=0.5,         # 30-30 seconds ke jhatke mein badhega
            help="0.5 Matlab 30 Seconds, 1.0 Matlab 1 Minute, 2.5 Matlab 2 Min 30 Sec"
        )
        # 🌟 UI UPGRADE: Professional status container
        st.info(f"📋 Configuration: **{platform}** Pipeline | Output Language: **{language}** (Change via Sidebar Control Panel)")
        submit_btn = st.form_submit_button("🚀 Launch AI Agents", use_container_width=True)

        if submit_btn:
            if user_niche:
                with st.spinner("🕵️ Multi-Agent System is orchestrating strategy..."):
                    try:
                        # 🌟 Form se duration bhej rahe hain backend mein
                        ai_output = run_my_crew_ai_agents(user_niche, platform, language, video_duration)
                        st.session_state["niche_data"]  = user_niche
                        st.session_state["script_data"] = ai_output
                        st.rerun() 
                    except Exception as e:
                        st.error(f"❌ Error: {e}")
            else:
                st.error("⚠️ Topic box mein kuch likho pehle!")

with tab2:
    st.header("📝 AI Script & Blueprint")
    st.write("---")
    if st.session_state["script_data"]:
        engine = st.session_state.get("active_model", "AI")
        pro_label = "Advanced Gemini Neural Core" if engine == "gemini" else "Hyper-Speed Multi-Agent Llama Architecture" if engine == "groq" else "Autonomous Multi-Agent AI System"
            
        st.success(f"🎉 Production Blueprint Ready! — Generated via **[{pro_label}]**")
        st.text_area("Generated Script Content:", value=st.session_state["script_data"], height=400)
        
        # 🌟 TWO DOWNLOAD BUTTONS SIDE-BY-SIDE USING COLUMNS
        col1, col2 = st.columns(2)
        
        with col1:
            st.download_button(
                label="📥 Download as Notepad (.txt)",
                data=st.session_state["script_data"],
                file_name=f"{platform}_{st.session_state['niche_data'].replace(' ','_')}.txt",
                mime="text/plain",
                use_container_width=True
            )
            
        with col2:
            # Word file memory object create karna button trigger hone par
            word_file = create_word_doc(st.session_state["script_data"], platform, st.session_state["niche_data"])
            st.download_button(
                label="📥 Download Word Document (.docx)",
                data=word_file,
                file_name=f"{platform}_{st.session_state['niche_data'].replace(' ','_')}.docx",
                mime="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                use_container_width=True
            )
    else:
        st.warning("⚠️ Pehle Tab 1 mein topic dalo aur agents run karo.")

with tab3:
    st.header("📊 Multi-Platform Report")
    st.write("---")
    # Columns setup code unchanged for data display placeholder
    c1, c2, c3 = st.columns(3)
    with c1: st.metric("YouTube Subs", "15,400", "+1,200")
    with c2: st.metric("Instagram Followers", "8,900", "+850")
    with c3: st.metric("X Impressions", "50K", "+12K")