# ── Groq Cache Fix ─────────────────────────────────────
try:
    from crewai.llms import cache as _cache
    _cache.mark_cache_breakpoint = lambda msg: msg
except ImportError:
    pass

import streamlit as st
import os
import io  # 🌟 NEW: Virtual Memory (RAM) ke liye
from docx import Document  # 🌟 NEW: Word Document Blueprint ke liye
from crewai import Agent, Task, Crew, LLM

st.set_page_config(page_title="Creator AI OS", layout="wide")

# ── API Keys ───────────────────────────────────────────
# ── STEP 1: TRIPLE-LAYER FAILPROOF LLM RESOLVER MATRIX ──
G_KEY_1 = st.secrets.get("GEMINI_API_KEY_1", "")
G_KEY_2 = st.secrets.get("GEMINI_API_KEY_2", "")
GR_KEY_1 = st.secrets.get("GROQ_API_KEY_1", "")
GR_KEY_2 = st.secrets.get("GROQ_API_KEY_2", "")
S_KEY_1 = st.secrets.get("SERPER_API_KEY_1", "")
S_KEY_2 = st.secrets.get("SERPER_API_KEY_2", "")

# Fallback mechanism standard keys for old dependencies
GEMINI_KEY = G_KEY_1 if G_KEY_1 else st.secrets.get("GEMINI_API_KEY", "")
GROQ_KEY   = GR_KEY_1 if GR_KEY_1 else st.secrets.get("GROQ_API_KEY", "")
SERPER_KEY = S_KEY_1 if S_KEY_1 else st.secrets.get("SERPER_API_KEY", "")

from crewai_tools import SerperDevTool
search_tool = SerperDevTool(api_key=SERPER_KEY) if SERPER_KEY else None

if not G_KEY_1 and not GR_KEY_1 and not GEMINI_KEY and not GROQ_KEY:
    st.sidebar.error("⚠️ Control Panel Matrix Empty: Keys Missing!")

def get_cluster_llm(provider="groq"):
    """
    Smart Fallback Rotation Router:
    - Groq Cluster: Key 1 -> Key 2 (High Speed Matrix)
    - Gemini Cluster: Key 1 -> Key 2 (Context Heavy Matrix)
    """
    if provider == "groq":
        primary_key = GR_KEY_1 if GR_KEY_1 else GROQ_KEY
        fallback_key = GR_KEY_2 if GR_KEY_2 else primary_key
        try:
            return LLM(model="groq/llama-3.3-70b-versatile", api_key=primary_key, timeout=30)
        except Exception as e:
            print(f"[ROUTING ALERT] Groq Key 1 failed. Swapping to Groq Key 2. Error: {e}")
            return LLM(model="groq/llama-3.3-70b-versatile", api_key=fallback_key, timeout=30)
    else:
        primary_key = G_KEY_1 if G_KEY_1 else GEMINI_KEY
        fallback_key = G_KEY_2 if G_KEY_2 else primary_key
        try:
            return LLM(model="gemini/gemini-2.5-flash", api_key=primary_key, timeout=30)
        except Exception as e:
            print(f"[ROUTING ALERT] Gemini Key 1 failed. Swapping to Gemini Key 2. Error: {e}")
            return LLM(model="gemini/gemini-2.5-flash", api_key=fallback_key, timeout=30)

# 🌟 NEW HELPER FUNCTION: Script ko Word File (.docx) me badalna RAM ke andar
def create_word_doc(script_text, platform_name, topic_name):
    doc = Document()
    
    # Word file ke andar ka styling aur content structure
    doc.add_heading(f"🎬 Production Blueprint: {topic_name}", level=1)
    doc.add_paragraph(f"Target Platform: {platform_name}")
    doc.add_paragraph("Generated by: Creator AI OS (Multi-Agent System)")
    doc.add_paragraph("="*50)
    
    doc.add_heading("📝 Video Script Content", level=2)
    doc.add_paragraph(script_text)
    
    # File ko temporary RAM memory me save karna
    bio = io.BytesIO()
    doc.save(bio)
    bio.seek(0)  # Pointer ko shuruat me lana download ke liye
    return bio
import requests
import json

def fetch_live_trends(niche_topic):
    """Serper API se direct live YouTube video links aur titles nikalna."""
    if not SERPER_KEY:
        return []
    
    url = "https://google.serper.dev/search"
    # Pure YouTube video data filter karne ke liye specific query vector
    payload = json.dumps({
        "q": f"site:youtube.com watch viral video {niche_topic}",
        "num": 5
    })
    headers = {
        'X-API-KEY': SERPER_KEY,
        'Content-Type': 'application/json'
    }
    
    video_trends = []
    try:
        response = requests.post(url, headers=headers, data=payload, timeout=10)
        data = response.json()
        
        if "organic" in data:
            for item in data["organic"]:
                link = item.get("link", "")
                # Sirf wahi links lenge jo direct valid YouTube video ke hain
                if "youtube.com/watch" in link or "youtu.be" in link:
                    video_trends.append({
                        "title": item.get("title", "Trending Video Blueprint"),
                        "url": link
                    })
                # Max 3 high-retention videos ka bracket lock karenge
                if len(video_trends) >= 3:
                    break
        return video_trends
    except Exception as e:
        print(f"[RADAR ERROR] Blueprint link extraction failed: {str(e)}")
        return []

# ── Session State ──────────────────────────────────────
if "niche_data"    not in st.session_state: st.session_state["niche_data"]    = ""
if "script_data"   not in st.session_state: st.session_state["script_data"]   = ""
if "active_model"  not in st.session_state: st.session_state["active_model"]  = ""
if "gemini_error"  not in st.session_state: st.session_state["gemini_error"]  = ""

# ── CrewAI Backend ─────────────────────────────────────
# =====================================================================
# ── STEP 2: THE ULTIMATE DYNAMIC MASTER CREW BACKEND ENGINE ──
# =====================================================================
# =====================================================================
# ── STEP 2: CLAUDE-APPROVED DEBUGGER ENGINE (VERBOSE ACTIVE) ──
# =====================================================================
def run_my_crew_ai_agents(niche_topic, social_platform, output_language, video_duration, app_mode, user_pasted_script, selected_bundle_options):
    """
    Lean Architecture Matrix with Active Verbose.
    Enforces single-shot processing to save tokens while keeping logs visible.
    """
    target_seconds = int(video_duration * 60)
    target_words = int(video_duration * 140)
    
    # Core Fast Clusters Routing From Step 1
    groq_cluster_llm = get_cluster_llm(provider="groq")
    gemini_cluster_llm = get_cluster_llm(provider="gemini")
    
    script_writing_llm = gemini_cluster_llm
    if not G_KEY_1 and not G_KEY_2 and not GEMINI_KEY:
        script_writing_llm = groq_cluster_llm

    # 🕵️ SPECIALIZED AGENTS - SINGLE CALL LOGS ENABLED
    trend_analyst = Agent(
        role="Fast Trend Spotter",
        goal=f"Extract minimal psychological hooks for '{niche_topic}' on {social_platform}.",
        backstory="You are a data-saving trend analyst. Give only raw data points.",
        llm=groq_cluster_llm,
        max_iter=1,              # 🌟 CLAUDE FIX: Loop control active
        max_rpm=5,               # 🌟 CLAUDE FIX: Rate protection
        verbose=True,            # 🌟 USER DEMAND: Terminal logs print honge!
        allow_delegation=False,
        memory=False             # 🌟 TOKEN SAVER: Disables internal memory overhead
    )

    script_writer = Agent(
        role="Humanized Script Writer",
        goal="Write a 2-column video script blueprint.",
        backstory="You write high-retention humanized content without any fluffy or robotic AI words.",
        llm=script_writing_llm,
        max_iter=1,              # 🌟 CLAUDE FIX: Loop control active
        max_rpm=5,
        verbose=True,            # 🌟 USER DEMAND: Terminal logs print honge!
        allow_delegation=False,
        memory=False
    )

    copy_maestro = Agent(
        role="Micro Copywriter",
        goal="Convert concepts into short social media assets.",
        backstory="You create titles, captions, layouts and threads instantly with extreme token efficiency.",
        llm=groq_cluster_llm,
        max_iter=1,              # 🌟 CLAUDE FIX: Loop control active
        max_rpm=5,
        verbose=True,            # 🌟 USER DEMAND: Terminal logs print honge!
        allow_delegation=False,
        memory=False
    )

    tasks_pipeline = []
    
    # 🌟 CLAUDE CHANGE 3: Research response format is strictly limited inside prompt
    research_task = Task(
        description=f"""Analyze viral hooks for '{niche_topic}' on {social_platform}.
        STRICT LIMIT: Response must be under 200 words only.
        Give ONLY 3 bullet points. No explanation, no intro.""",
        expected_output="3 bullet points under 200 words total.",
        agent=trend_analyst
    )
    tasks_pipeline.append(research_task)

    # Deliverable Tier 1: Audio/Visual Content Script Layout
    if any("Script" in opt for opt in selected_bundle_options):
        script_prompt = f"Write a full high-retention video script for '{niche_topic}' targeting around {target_words} words ({target_seconds} seconds duration)."
        if app_mode == "✍️ Repurpose My Script Mode":
            script_prompt = f"Analyze this raw user script: '{user_pasted_script}'. Re-engineer and polish it for ultimate human cadence."
            
        script_task = Task(
            description=f"""{script_prompt} Flawlessly match language and cultural rhythm to '{output_language}'.
            Output ONLY in a professional 2-Column Audio/Visual markdown table layout.
            Ensure zero AI-watermark words. Avoid: delve, moreover, testament, in conclusion.
            
            🌟 EXAMPLE SHOT-PROMPTING FORMAT:
            | [00:00-00:05] | Camera zooms in sharply | Kya tumhe pata hai AI kya sochta hai? |
            | [00:05-00:15] | Cut to diagram layout | Context window woh jagah hai jahan... |""",
            expected_output="Conversational script inside an Audio/Visual 2-column table grid.",
            agent=script_writer,
            context=[research_task]  # Light short context passed
        )
        tasks_pipeline.append(script_task)

    # 🌟 CLAUDE CHANGE 1: Independent Distribution Task (Context completely removed to save 4000 tokens)
    dist_requirements = []
    if any("Titles" in opt for opt in selected_bundle_options): dist_requirements.append("- 5 High-CTR Titles & Search-Engine Descriptions")
    if any("Thumbnail" in opt for opt in selected_bundle_options): dist_requirements.append("- 3 distinct thumbnail frameworks (Focal point, Text overlay hook max 3 words, Contrast colors)")
    if any("Captions" in opt for opt in selected_bundle_options): dist_requirements.append("- 3 click-driven micro-captions and hashtag nodes for Shorts feed")
    if any("Threads" in opt for opt in selected_bundle_options): dist_requirements.append("- 5-part vertical engagement X Thread and authoritative LinkedIn post")

    if dist_requirements:
        distribution_task = Task(
            description=f"""You are an independent expert copywriter working directly from the primary topic details.
            Topic: '{niche_topic}' | Platform: {social_platform} | Language: {output_language}
            
            Generate ONLY the required structural assets below:
            {chr(10).join(dist_requirements)}
            
            Rules:
            - NO robotic words: delve, moreover, testament, in conclusion, furthermore
            - Be direct, highly human, conversational, and punchy
            - Each individual component item output must be concise and max 150 words
            - Zero explanation, zero preamble chitchat, output raw ready-to-copy content only.""",
            expected_output="Requested distribution assets package, no extra commentary.",
            agent=copy_maestro
            # Context intentionally removed here to instantly optimize prompt size!
        )
        tasks_pipeline.append(distribution_task)

    # 🏁 LEAN PRODUCTION LAUNCHER
    master_crew = Crew(
        agents=[trend_analyst, script_writer, copy_maestro],
        tasks=tasks_pipeline,
        verbose=True,            # 🌟 USER DEMAND: Terminal logs visible
        process='sequential'
    )
    
    return master_crew.get_output() if hasattr(master_crew, 'get_output') else master_crew.kickoff()

# ── Sidebar ────────────────────────────────────────────
with st.sidebar:
    st.title("⚙️ Control Panel")
    platform = st.selectbox("Platform:", ["YouTube", "Instagram", "Facebook", "X (Twitter)"])
    language = st.selectbox("Language:", ["Hinglish", "Hindi", "English"])
    st.write("---")
    st.caption("Powered by Gemini + Groq & CrewAI")

# ── Main UI ────────────────────────────────────────────
st.title("🚀 Creator AI Manager")
st.write(f"**{platform}** manager active | Language: **{language}**")
st.write("---")

tab1, tab2, tab3 = st.tabs(["🔥 Trend & Script", "📝 Generated Script", "📊 Analytics"])

# ── HELPER: Radar Data Fetcher (Isse app.py ke top level ya functions ke saath rakho)
def fetch_radar_data(niche, show_videos, show_thumbnails):
    """Conditional data fetching to save API tokens."""
    results = {"videos": [], "thumbnails": []}
    if not SERPER_KEY: return results
    
    # 1. Fetch Videos if requested
    if show_videos:
        url = "https://google.serper.dev/search"
        payload = json.dumps({"q": f"site:youtube.com watch viral video {niche}", "num": 3})
        try:
            response = requests.post(url, headers={'X-API-KEY': SERPER_KEY, 'Content-Type': 'application/json'}, data=payload, timeout=5)
            data = response.json()
            if "organic" in data:
                results["videos"] = [v for v in data["organic"] if "youtube.com" in v.get("link", "")]
        except: pass

    # 2. Fetch Thumbnails if requested (Specific query for visual research)
    if show_thumbnails:
        url = "https://google.serper.dev/images"
        payload = json.dumps({"q": f"youtube thumbnail {niche} viral design", "num": 3})
        try:
            response = requests.post(url, headers={'X-API-KEY': SERPER_KEY, 'Content-Type': 'application/json'}, data=payload, timeout=5)
            data = response.json()
            if "images" in data:
                results["thumbnails"] = data["images"][:3]
        except: pass
    
    return results

# ── tab1 DEFINITION ────────────────────────────────────
# =====================================================================
# ── STEP 3: THE STATE-LOCKED DYNAMIC TAB 1 INTERACTION HUB ──
# =====================================================================
with tab1:
    st.markdown("### 🔥 AI Content Strategy Hub")
    st.caption("Topic/Script daliye — Specialized multi-agent network kaam karega.")
    st.write("---")
    
    # Radio buttons form ke bahar hain taaki UI click karte hi responsive rahe
    app_mode = st.radio(
        "🔮 Kis Mode me kaam karna hai?", 
        ["🚀 Complete Blueprint Mode", "✍️ Repurpose My Script Mode"], 
        horizontal=True
    )
    st.write("---")
    
    # Initial empty variables backup setup
    bundle_options = []
    user_niche = ""
    user_pasted_script = ""
    video_duration = 2.0
    
    with st.form("trend_form"):
        # 🟢 CONFIGURATION FOR MODE 1: COMPLETE BLUEPRINT
        # Purana st.multiselect hata kar ye premium pills laga do:
        if app_mode == "🚀 Complete Blueprint Mode":
            bundle_options = st.pills(
                "🎁 Is Content Production Bundle me kya-kya generate karna hai? (Multi-Select Available)", 
                ["🎬 Retention Script & Visual Cues", "🎯 High-CTR Viral Titles & Descriptions", "🎨 High-CTR Thumbnail Design Concepts", "📱 Shorts/Reels Viral Captions & Tags", "🧵 LinkedIn & X (Twitter) Threads"],
                default=[],
                selection_mode="multi",
                key="blueprint_opts"
            )
            user_niche = st.text_input("🎯 Kis topic par video banani hai?", value=st.session_state.get("niche_data", ""))
            # 🌟 GUARDRAIL FIXED: Slider max limit ab 20.0 se घटकर 3.0 mins ho gayi hai (Token Protection Active)
            video_duration = st.slider("⏱ Video ki duration kitni honi chahiye? (In Minutes)", 0.5, 3.0, 1.0, 0.5)
            
        # 🟠 CONFIGURATION FOR MODE 2: REPURPOSE EXISTING SCRIPT
        # Purana st.multiselect yahan se bhi hata kar pills laga do:
        else:
            bundle_options = st.pills(
                "🎁 Apni Paste ki hui Script se kya-kya extract/generate karna hai? (Multi-Select Available)", 
                ["🎯 High-CTR Viral Titles & Descriptions", "🎨 High-CTR Thumbnail Design Concepts", "📱 Shorts/Reels Viral Captions & Tags", "🧵 LinkedIn & X (Twitter) Threads"],
                default=[],
                selection_mode="multi",
                key="repurpose_opts"
            )
            user_niche = st.text_input("🎯 Video ka Main Topic/Title:", value=st.session_state.get("niche_data", ""))
            user_pasted_script = st.text_area("📝 Apni pehle se likhi hui Script yahan Paste karein:", height=200)

        submit_btn = st.form_submit_button("🚀 Launch Specialized Agents Grid", use_container_width=True)

        # New Verification: Check if bundle_options is empty
        if submit_btn:
            if not bundle_options:
                st.error("⚠️ Oye Founder! Pehle niche bundle options me se kam se kam ek cheez toh select karo!")
            elif user_niche:
                st.session_state["niche_data"] = user_niche
                st.session_state["form_submitted"] = True
                st.session_state["selected_options"] = bundle_options
                st.session_state["current_mode"] = app_mode
                st.session_state["pasted_script"] = user_pasted_script
                st.session_state["duration"] = video_duration
            else:
                st.error("⚠️ Topic box mein kuch likho pehle!")

    # 📡 THE REAL-TIME SMART MARKET RADAR LOGIC
    current_opts = st.session_state.get("selected_options", bundle_options)
    target_niche = st.session_state.get("niche_data", "")
    
    # Check variables strings mapping for condition extraction logic
    is_script_req = any("Script" in b for b in current_opts)
    is_thumb_req = any("Thumbnail" in b for b in current_opts)
    
    if target_niche and (is_script_req or is_thumb_req):
        st.write("---")
        st.markdown("### 📡 Real-Time Market Intelligence Radar")
        
        with st.spinner("Scanning viral distribution layers..."):
            # Purana helper fetch_live_trends engine trigger integration
            live_trends_data = fetch_live_trends(target_niche)
        
        # Displaying YouTube video structures matching the query link logs
        if live_trends_data:
            st.markdown("##### 📈 Trending YouTube Structures Found")
            cols_layout = st.columns(len(live_trends_data))
            for idx, item in enumerate(live_trends_data):
                with cols_layout[idx]:
                    st.write(f"🔗 **[{item['title']}]({item['url']})**")
                    st.video(item['url'])
        else:
            st.info("🚀 **High-Alpha Opportunity Detected!** Zero direct identical competition discovered for this exact angle—this is a pure Blue Ocean play.")

    # ⚡ AUTOMATED BACKEND PIPELINE GENERATION TRIGGER GATE
    # ⚡ AUTOMATED BACKEND PIPELINE GENERATION TRIGGER GATE (FIXED STORAGE)
    if st.session_state.get("form_submitted"):
        with st.spinner("🕵️ Orchestrating failproof master crew network..."):
            try:
                ai_output = run_my_crew_ai_agents(
                    st.session_state["niche_data"],
                    platform if 'platform' in globals() else "YouTube",
                    language if 'language' in globals() else "Hindi",
                    st.session_state.get("duration", 2.0),
                    st.session_state["current_mode"],
                    st.session_state.get("pasted_script", ""),
                    st.session_state["selected_options"]
                )
                
                # 🌟 FIXED: Ab dono options ka data alag variables me save hoga taaki data lose na ho!
                st.session_state["script_data"] = ai_output  # Universal backup
                
                if st.session_state["current_mode"] == "🚀 Complete Blueprint Mode":
                    st.session_state["blueprint_final_output"] = ai_output
                else:
                    st.session_state["repurpose_final_output"] = ai_output
                    
                st.session_state["form_submitted"] = False
                st.success("🎉 Crew Execution Successful! Check Tab 2 for your optimized script & assets.")
                st.rerun()
            except Exception as e:
                st.session_state["form_submitted"] = False
                st.error(f"🤖 Engine Error: {str(e)}")

with tab2:
    st.header("📥 Download Generated Content")
    st.write("---")
    
    # 🌟 FIXED: Dynamic data fetcher logic
    display_content = ""
    if "blueprint_final_output" in st.session_state and st.session_state.get("current_mode") == "🚀 Complete Blueprint Mode":
        display_content = st.session_state["blueprint_final_output"]
    elif "repurpose_final_output" in st.session_state:
        display_content = st.session_state["repurpose_final_output"]
    elif "script_data" in st.session_state:
        display_content = st.session_state["script_data"]

    if display_content:
        # Markdown visualization preview box
        st.subheader("📝 Live Content Preview")
        st.markdown(display_content)
        st.write("---")
        
        # DOWNLOADING BUTTONS PIPELINE USING COLUMNS
        col1, col2 = st.columns(2)
        
        with col1:
            st.download_button(
                label="📥 Download as Notepad (.txt)",
                data=str(display_content),
                file_name=f"Script_{st.session_state.get('niche_data', 'content').replace(' ','_')}.txt",
                mime="text/plain",
                use_container_width=True
            )
            
        with col2:
            word_file = create_word_doc(str(display_content), "Social_Media", st.session_state.get("niche_data", "Content"))
            st.download_button(
                label="📥 Download Word Document (.docx)",
                data=word_file,
                file_name=f"Script_{st.session_state.get('niche_data', 'content').replace(' ','_')}.docx",
                mime="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                use_container_width=True
            )
    else:
        st.warning("⚠️ Pehle Tab 1 mein topic dalo aur agents run karo. Agar pehle run kiya tha, toh current mode switch karne par naya trigger click karein!")

with tab3:
    st.header("📊 Multi-Platform Report")
    st.write("---")
    # Columns setup code unchanged for data display placeholder
    c1, c2, c3 = st.columns(3)
    with c1: st.metric("YouTube Subs", "15,400", "+1,200")
    with c2: st.metric("Instagram Followers", "8,900", "+850")
    with c3: st.metric("X Impressions", "50K", "+12K")