# helpers.py
import re
import io
from docx import Document

def parse_blueprint_metadata(raw_text):
    """
    Takes the raw text from CrewAI, slices it based on exact headings using Regex, 
    and returns a formatted dictionary for Tab 3 UI boxes.
    """
    metadata = {
        "yt_title": "",
        "yt_desc": "",
        "linkedin_post": "",
        "tw_thread": "",
        "ig_caption": ""
    }
    
    title_match = re.search(r"Title:\s*(.*?)(?=\nDescription:|\nLinkedIn Post:|\nTwitter Thread:|$)", raw_text, re.IGNORECASE | re.DOTALL)
    if title_match:
        metadata["yt_title"] = title_match.group(1).strip()
        
    desc_match = re.search(r"Description:\s*(.*?)(?=\nLinkedIn Post:|\nTwitter Thread:|$)", raw_text, re.IGNORECASE | re.DOTALL)
    if desc_match:
        metadata["yt_desc"] = desc_match.group(1).strip()
        
    linkedin_match = re.search(r"LinkedIn Post:\s*(.*?)(?=\nTwitter Thread:|$)", raw_text, re.IGNORECASE | re.DOTALL)
    if linkedin_match:
        metadata["linkedin_post"] = linkedin_match.group(1).strip()
        
    twitter_match = re.search(r"Twitter Thread:\s*(.*?)(?=$)", raw_text, re.IGNORECASE | re.DOTALL)
    if twitter_match:
        metadata["tw_thread"] = twitter_match.group(1).strip()
        
    ig_match = re.search(r"Instagram Caption:\s*(.*?)(?=$)", raw_text, re.IGNORECASE | re.DOTALL)
    if ig_match:
        metadata["ig_caption"] = ig_match.group(1).strip()
        
    return metadata

def create_word_doc(script_text, platform_name, topic_name):
    """
    Generates a downloadable MS Word document.
    """
    doc = Document()
    doc.add_heading(f"🎬 Production Blueprint: {topic_name}", level=1)
    doc.add_paragraph(f"Target Platform: {platform_name}")
    doc.add_paragraph("Generated by: Creator AI OS (Multi-Agent System)")
    doc.add_paragraph("="*50)
    doc.add_heading("📝 Video Script Content", level=2)
    
    lines = script_text.split('\n')
    for line in lines:
        clean_line = line.strip()
        clean_line = clean_line.replace('### ', '') 
        
        if clean_line:
            doc.add_paragraph(clean_line)
            
    bio = io.BytesIO()
    doc.save(bio)
    bio.seek(0)
    return bio