# helpers.py
import re
import io
from docx import Document

def parse_blueprint_metadata(raw_text):
    """
    AI text se metadata extract karne ka fail-proof regex parser.
    """
    parsed_data = {
        "yt_title": "",
        "yt_desc": "",
        "tw_thread": "",
        "ig_caption": "",
        "li_post": "",
        "hooks": []
    }
    
    if not raw_text:
        return parsed_data

    # 1. Extract Hooks (Tumhare app.py logic ko support karne ke liye)
    extracted_hooks = re.findall(r'(?:Hook|Retention):\s*"?([^"\n]+)"?', raw_text, re.IGNORECASE)
    parsed_data["hooks"] = [h.strip() for h in extracted_hooks if h.strip()]

    # 2. Extract YouTube Title (Bohot flexible rakha hai)
    yt_title_match = re.search(r'(?:YouTube Title|Title):\s*(.*?)(?=\n|$)', raw_text, re.IGNORECASE)
    if yt_title_match:
        # Faltu brackets aur quotes hata do
        clean_title = yt_title_match.group(1).replace("[YOUTUBE SHORTS TITLE]", "").replace('"', '').replace('[', '').replace(']', '').strip()
        parsed_data["yt_title"] = clean_title

    # 3. Extract YouTube Description
    yt_desc_match = re.search(r'(?:YouTube Description|Description):\s*(.*?)(?:\[?TWITTER|\[?INSTA|\[?LINKEDIN|\[?X THREAD|$)', raw_text, re.IGNORECASE | re.DOTALL)
    if yt_desc_match:
        # Pata chala usme koi faltu spaces hain toh unko clean kar dega
        parsed_data["yt_desc"] = yt_desc_match.group(1).strip()

    # 4. Extract Twitter/X Thread (Sabse important)
    # Yeh dekhega ki "TWITTER" ya "X THREAD" kahan likha hai, aur wahan se lekar agle section tak sab utha lega
    tw_match = re.search(r'(?:\[?TWITTER.*?THREAD.*?\]?)(.*?)(?:\[?INSTAGRAM|\[?LINKEDIN|\[?YOUTUBE|$)', raw_text, re.IGNORECASE | re.DOTALL)
    if tw_match:
        thread_content = tw_match.group(1).strip()
        # Agar start mein koi faltu dash ya space hai toh hata do
        parsed_data["tw_thread"] = thread_content.lstrip('-').strip()

    # 5. Extract Instagram/Facebook Caption
    ig_match = re.search(r'(?:\[?INSTA.*?CAPTION.*?\]?)(.*?)(?:\[?LINKEDIN|\[?TWITTER|\[?YOUTUBE|$)', raw_text, re.IGNORECASE | re.DOTALL)
    if ig_match:
        parsed_data["ig_caption"] = ig_match.group(1).strip()

    # 6. Extract LinkedIn Post
    li_match = re.search(r'(?:\[?LINKEDIN.*?POST.*?\]?)(.*?)(?:\[?INSTAGRAM|\[?TWITTER|\[?YOUTUBE|$)', raw_text, re.IGNORECASE | re.DOTALL)
    if li_match:
        parsed_data["li_post"] = li_match.group(1).strip()

    return parsed_data

def create_word_doc(script_text, platform_name, topic_name):
    """
    Generates a downloadable MS Word document.
    """
    doc = Document()
    doc.add_heading(f"🎬 Production Blueprint: {topic_name}", level=1)
    doc.add_paragraph(f"Target Platform: {platform_name}")
    doc.add_paragraph("Generated by: Creator AI OS (Multi-Agent System)")
    doc.add_paragraph("="*50)
    doc.add_heading("📝 Video Script Content", level=2)
    
    lines = script_text.split('\n')
    for line in lines:
        clean_line = line.strip()
        clean_line = clean_line.replace('### ', '') 
        
        if clean_line:
            doc.add_paragraph(clean_line)
            
    bio = io.BytesIO()
    doc.save(bio)
    bio.seek(0)
    return bio